parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
env:
  es6: true
  browser: true
  cypress/globals: true
plugins: ["prettier", "cypress", "svelte3"]
extends: ["eslint:recommended"]
overrides:
  - files: ["*.svelte"]
    processor: "svelte3/svelte3"
rules:
  prettier/prettier: "error"
