name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn run lint
    - name: Audit
      run: yarn audit
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
    - name: Upload files
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: -m cp public/* gs://retrograde.dyl.dog/
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT }}