name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Audit
      run: yarn audit
    - name: Build
      run: yarn build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: public

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v1
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: public
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
    - name: Install gcloud Beta Components
      run: gcloud components install beta
    - name: Deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}