name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Audit
      run: yarn audit
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
    - name: Docker build
      uses: docker://gcr.io/cloud-builders/docker
      with:
        args: build . -t gcr.io/retrograde/retrograde.js:latest
    - name: Docker push
      run: gcloud auth configure-docker && docker push gcr.io/retrograde/retrograde.js:latest